### ISSUE TITLE
As there are so many developers in China, I sincerely request for translating the document in Chinese

### ISSUE THREAD

**Issue by wangjunchao** [Qiskit/qiskit-translations#31]
Hi,

There are so many developers in China. I'd like to call for translating the documents into Chinese to make more Chinese quantum developers easily access the achievement made by IBM in this field. I found there are so many researchers and students around me want to use the Qiskit, but most of them are not good at English. 

I have already done some translations for a small piece of the documents with the following link:
[(https://qiskit.org/documentation/api/qiskit.aqua.algorithms.single_sample.HHL.html]

A lot of researchers and students around me really like it. So I request for translating the useful documents into Chinese if possible.

**Comment by SooluThomas** [comment]
Hi @wangjunchao, at this time, due to transition in the supporting team, no new languages will be added to the documentation. However, please continue to open issues to recruit translation team members and let us know which languages you want for when we get started again!

There's another open Issue #10 for adding Chinese translations. So further follow-up can be made in the other issue. Thanks for your interest! 😊
